# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createEditTask.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 450)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        MainWindow.setMaximumSize(QtCore.QSize(600, 450))
        MainWindow.setStyleSheet("#centralwidget {\n"
"    padding: 20px;\n"
"}\n"
"\n"
"#planLabel {\n"
"    font-size: 50px;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #fff\n"
"}\n"
"\n"
"QPushButton[plan=\'true\'] {\n"
"    background-color: #54ad54;\n"
"    border: none;\n"
"    border-radius: 0.25em;\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QPushButton[small=\'true\'] {\n"
"    background-color: #999;\n"
"    border: none;\n"
"    border-radius: 0.25em;\n"
"    color: #fff;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton[plan=\'true\']:hover {\n"
"    background-color: #288b28;\n"
"}\n"
"\n"
"QPushButton[small=\'true\']:hover {\n"
"    background-color: #777;\n"
"}\n"
"\n"
"QPushButton[plan=\'true\']:pressed {\n"
"    background-color: #246024;\n"
"}\n"
"\n"
"QPushButton[small=\'true\']:pressed {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"#deleteBtn {\n"
"    border: none;/* 1px solid red;*/\n"
"/*    background-color: #F34235;*/\n"
"    background-color: #DC3545;\n"
"    border-radius: 0.25em;\n"
"    /*background-image: url(bin.png);*/\n"
"}\n"
"\n"
"#deleteBtn:hover {\n"
"    background-color: #BB2D3B;\n"
"}\n"
"\n"
"#saveBtn {\n"
"    background-color: #0D6EFD;\n"
"    border: none;\n"
"    border-radius: 0.25em;\n"
"    color: #fff;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#saveBtn:hover {\n"
"    background-color: #0B5ED7;\n"
"}\n"
"\n"
"#saveBtn:pressed {\n"
"    background-color: #0B5ED7;\n"
"}\n"
"\n"
"#titleInput, #categoryInput, #deadlineInput, #descriptionInput {\n"
"    border: 1px solid #ccc;\n"
"    border-bottom: 1px solid #54ad54;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(images/drop-down-list.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    image: url(images/drop-down-list-toggle.png);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 1px solid #ccc;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(images/drop-down-list.png);\n"
"}\n"
"\n"
"QDateEdit::up-arrow {\n"
"    image: url(images/drop-down-list-toggle.png);\n"
"}\n"
"\n"
"QDateEdit::up-button {\n"
"    border-left: 1px solid #ccc;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QDateEdit::down-button {\n"
"    border-left: 1px solid #ccc;\n"
"}\n"
"\n"
"QDateEdit:disabled {\n"
"    background-color: #eee;\n"
"}\n"
"/*\n"
"QDateEdit::up-button:hover {\n"
"    background-color: #ccc;\n"
"}\n"
"\n"
"QDateEdit::up-button:pressed {\n"
"    background-color: #ccc;\n"
"}\n"
"\n"
"QDateEdit::down-button:hover {\n"
"    background-color: #ccc;\n"
"}\n"
"*/\n"
"#titleLabel, #categoryLabel, #repeatLabel, #deadlineCheckBox, #descriptionLabel {\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#deadlineCheckBox {\n"
"    background-color: #fff\n"
"}\n"
"\n"
"#cancelBtn {\n"
"    background-color: #999;\n"
"    border: none;\n"
"    border-radius: 0.25em;\n"
"    color: #fff;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#cancelBtn:hover {\n"
"    background-color: #777;\n"
"}\n"
"\n"
"#cancelBtn:pressed {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"#loadImageBtn {\n"
"    border: none;/* 1px solid red;*/\n"
"    background-color: #FFC107;\n"
"    border-radius: 0.25em;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#loadImageBtn:hover {\n"
"    background-color: #FFCA2C\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windowLabel = QtWidgets.QLabel(self.centralwidget)
        self.windowLabel.setStyleSheet("font-size: 20px")
        self.windowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.windowLabel.setIndent(0)
        self.windowLabel.setObjectName("windowLabel")
        self.verticalLayout.addWidget(self.windowLabel)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setIndent(5)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.titleInput = QtWidgets.QLineEdit(self.centralwidget)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.categoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.categoryLabel.setIndent(5)
        self.categoryLabel.setObjectName("categoryLabel")
        self.verticalLayout.addWidget(self.categoryLabel)
        self.categoryInput = QtWidgets.QComboBox(self.centralwidget)
        self.categoryInput.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.categoryInput.setObjectName("categoryInput")
        self.verticalLayout.addWidget(self.categoryInput)
        self.repeatLabel = QtWidgets.QLabel(self.centralwidget)
        self.repeatLabel.setEnabled(True)
        self.repeatLabel.setIndent(5)
        self.repeatLabel.setObjectName("repeatLabel")
        self.verticalLayout.addWidget(self.repeatLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MondayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MondayBtn.setEnabled(True)
        self.MondayBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.MondayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MondayBtn.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.MondayBtn.setProperty("isChecked", True)
        self.MondayBtn.setObjectName("MondayBtn")
        self.weekButtons = QtWidgets.QButtonGroup(MainWindow)
        self.weekButtons.setObjectName("weekButtons")
        self.weekButtons.addButton(self.MondayBtn)
        self.horizontalLayout_2.addWidget(self.MondayBtn)
        self.TuesdayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TuesdayBtn.setEnabled(True)
        self.TuesdayBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.TuesdayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TuesdayBtn.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.TuesdayBtn.setProperty("isChecked", True)
        self.TuesdayBtn.setObjectName("TuesdayBtn")
        self.weekButtons.addButton(self.TuesdayBtn)
        self.horizontalLayout_2.addWidget(self.TuesdayBtn)
        self.WednesDay = QtWidgets.QPushButton(self.centralwidget)
        self.WednesDay.setEnabled(True)
        self.WednesDay.setMinimumSize(QtCore.QSize(0, 25))
        self.WednesDay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.WednesDay.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.WednesDay.setProperty("isChecked", True)
        self.WednesDay.setObjectName("WednesDay")
        self.weekButtons.addButton(self.WednesDay)
        self.horizontalLayout_2.addWidget(self.WednesDay)
        self.ThursdayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ThursdayBtn.setEnabled(True)
        self.ThursdayBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.ThursdayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ThursdayBtn.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.ThursdayBtn.setProperty("isChecked", True)
        self.ThursdayBtn.setObjectName("ThursdayBtn")
        self.weekButtons.addButton(self.ThursdayBtn)
        self.horizontalLayout_2.addWidget(self.ThursdayBtn)
        self.FridayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FridayBtn.setEnabled(True)
        self.FridayBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.FridayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FridayBtn.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.FridayBtn.setProperty("isChecked", True)
        self.FridayBtn.setObjectName("FridayBtn")
        self.weekButtons.addButton(self.FridayBtn)
        self.horizontalLayout_2.addWidget(self.FridayBtn)
        self.SaturdayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaturdayBtn.setEnabled(True)
        self.SaturdayBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.SaturdayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaturdayBtn.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.SaturdayBtn.setProperty("isChecked", True)
        self.SaturdayBtn.setObjectName("SaturdayBtn")
        self.weekButtons.addButton(self.SaturdayBtn)
        self.horizontalLayout_2.addWidget(self.SaturdayBtn)
        self.SundayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SundayBtn.setEnabled(True)
        self.SundayBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.SundayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SundayBtn.setStyleSheet("background-color: #0f0;\n"
"    border: 1px solid #ddd;")
        self.SundayBtn.setProperty("isChecked", True)
        self.SundayBtn.setObjectName("SundayBtn")
        self.weekButtons.addButton(self.SundayBtn)
        self.horizontalLayout_2.addWidget(self.SundayBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.deadlineFrame = QtWidgets.QFrame(self.centralwidget)
        self.deadlineFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.deadlineFrame.setStyleSheet("")
        self.deadlineFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deadlineFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deadlineFrame.setObjectName("deadlineFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.deadlineFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deadlineLayout = QtWidgets.QHBoxLayout()
        self.deadlineLayout.setSpacing(6)
        self.deadlineLayout.setObjectName("deadlineLayout")
        self.deadlineCheckBox = QtWidgets.QCheckBox(self.deadlineFrame)
        self.deadlineCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deadlineCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deadlineCheckBox.setAutoFillBackground(False)
        self.deadlineCheckBox.setStyleSheet("")
        self.deadlineCheckBox.setChecked(False)
        self.deadlineCheckBox.setAutoRepeat(False)
        self.deadlineCheckBox.setObjectName("deadlineCheckBox")
        self.deadlineLayout.addWidget(self.deadlineCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deadlineLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.deadlineLayout)
        self.verticalLayout.addWidget(self.deadlineFrame)
        self.deadlineInput = QtWidgets.QDateEdit(self.centralwidget)
        self.deadlineInput.setEnabled(False)
        self.deadlineInput.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deadlineInput.setObjectName("deadlineInput")
        self.verticalLayout.addWidget(self.deadlineInput)
        self.descriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.descriptionLabel.setIndent(5)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.descriptionInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.descriptionInput.setObjectName("descriptionInput")
        self.verticalLayout.addWidget(self.descriptionInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setMinimumSize(QtCore.QSize(120, 0))
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.loadImageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.loadImageBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loadImageBtn.setObjectName("loadImageBtn")
        self.horizontalLayout.addWidget(self.loadImageBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setMinimumSize(QtCore.QSize(120, 0))
        self.saveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание дела"))
        self.windowLabel.setText(_translate("MainWindow", "Создание дела"))
        self.titleLabel.setText(_translate("MainWindow", "Название:"))
        self.categoryLabel.setText(_translate("MainWindow", "Категория:"))
        self.repeatLabel.setText(_translate("MainWindow", "Повтор:"))
        self.MondayBtn.setText(_translate("MainWindow", "ПН"))
        self.TuesdayBtn.setText(_translate("MainWindow", "ВТ"))
        self.WednesDay.setText(_translate("MainWindow", "СР"))
        self.ThursdayBtn.setText(_translate("MainWindow", "ЧТ"))
        self.FridayBtn.setText(_translate("MainWindow", "ПТ"))
        self.SaturdayBtn.setText(_translate("MainWindow", "СБ"))
        self.SundayBtn.setText(_translate("MainWindow", "ВС"))
        self.deadlineCheckBox.setText(_translate("MainWindow", "Дедлайн"))
        self.descriptionLabel.setText(_translate("MainWindow", "Описание:"))
        self.cancelBtn.setText(_translate("MainWindow", "Отмена"))
        self.loadImageBtn.setText(_translate("MainWindow", "Загрузить картинку"))
        self.saveBtn.setText(_translate("MainWindow", "Добавить"))
