# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reminder.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 450)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        MainWindow.setMaximumSize(QtCore.QSize(600, 450))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #fff\n"
"}\n"
"\n"
"#addBtn {\n"
"    background-color: #0D6EFD;\n"
"    border: none;\n"
"    border-radius: 0.25em;\n"
"    color: #fff;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#addBtn:hover {\n"
"    background-color: #0B5ED7;\n"
"}\n"
"\n"
"#addBtn:pressed {\n"
"    background-color: #0B5ED7;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow {\n"
"    image: url(images/drop-down-list.png);\n"
"}\n"
"\n"
"QTimeEdit::up-arrow {\n"
"    image: url(images/drop-down-list-toggle.png);\n"
"}\n"
"\n"
"QTimeEdit::up-button {\n"
"    border-left: 1px solid #ccc;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTimeEdit::down-button {\n"
"    border-left: 1px solid #ccc;\n"
"}\n"
"\n"
"#deadlineCheckBox {\n"
"    background-color: #fff\n"
"}\n"
"\n"
"#cancelBtn {\n"
"    background-color: #999;\n"
"    border: none;\n"
"    border-radius: 0.25em;\n"
"    color: #fff;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#cancelBtn:hover {\n"
"    background-color: #777;\n"
"}\n"
"\n"
"#cancelBtn:pressed {\n"
"    background-color: #555;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font-size: 24px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.dateInput = QtWidgets.QCalendarWidget(self.centralwidget)
        self.dateInput.setMinimumSize(QtCore.QSize(0, 230))
        self.dateInput.setObjectName("dateInput")
        self.verticalLayout_2.addWidget(self.dateInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.descriptionInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.descriptionInput.setObjectName("descriptionInput")
        self.horizontalLayout.addWidget(self.descriptionInput)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.timeInput = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeInput.setStyleSheet("font-size: 28px")
        self.timeInput.setObjectName("timeInput")
        self.verticalLayout.addWidget(self.timeInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout_2.addWidget(self.addBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Поставить напоминание"))
        self.label.setText(_translate("MainWindow", "Поставить напоминание"))
        self.descriptionInput.setPlaceholderText(_translate("MainWindow", "Описание..."))
        self.label_2.setText(_translate("MainWindow", "Выберите время:"))
        self.cancelBtn.setText(_translate("MainWindow", "Отмена"))
        self.addBtn.setText(_translate("MainWindow", "Поставить"))
